name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to trigger terraform destroy'
        required: false
        default: 'false'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          TF_VAR_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=plan.tfplan
        env:
          TF_VAR_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        working-directory: terraform
        if: github.ref == 'refs/heads/main' && github.event.inputs.destroy != 'true'
        run: terraform apply -auto-approve plan.tfplan
        env:
          TF_VAR_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event.inputs.destroy == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          TF_VAR_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
        env:
          TF_VAR_credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
