name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Setup Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/key.json

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/key.json

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=plan.tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/key.json

      - name: Terraform Apply
        working-directory: terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve plan.tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/key.json
